server:
  port: 4566

spring:
  application:
    name: credit-command-service
  datasource:
    url: jdbc:postgresql://localhost:5432/creditdb
    username: admin
    password: admin
  jpa:
    hibernate:
      ddl-auto: update
