server:
  port: 4568

spring:
  jackson:
    time-zone: GMT+3
  application:
    name: credit-query-service
  data:
    redis:
      host: localhost
      port: 6379
      database: 0
    mongodb:
      host: localhost
      port: 27017
      database: creditdb
      authentication-database: admin
      username: root
      password: root
  kafka:
    retry:
      topic:
        attempts: 5
        enabled: true
        delay: 1000
        max-delay: 30000
        multiplier: 1.5
    consumer:
      bootstrap-servers: localhost:29092
      group-id: credit-query-service
      auto-offset-reset: latest
      enable-auto-commit: false
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    listener:
      ack-mode: manual
  cache:
    type: redis

config:
  idempotency:
    credit: 1
    installment: 2


logging:
  pattern:
    console: "%clr(%d{${LOG_DATEFORMAT_PATTERN:yyyy-MM-dd HH:mm:ss.SSS, Europe/Rome}}){faint} %clr(${LOG_LEVEL_PATTERN:-%5p}) %clr[%mdc{UUID}] %clr(${PID:- }){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n${LOG_EXCEPTION_CONVERSION_WORD:-%wEx}"
  level:
    root: info
    org.colendi: debug
    org.springframework: info
