server:
  port: 4567

spring:
  application:
    name: credit-command-service
  datasource:
    url: jdbc:postgresql://localhost:5432/creditdb
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update

logging:
  level:
    root: info
    org.colendi: debug
    org.springframework: info
